FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

# Install required libraries
RUN pip install fastapi prometheus-fastapi-instrumentator

# Copy your FastAPI code into the container
COPY ./app /app

# Expose the Prometheus and FastAPI ports
EXPOSE 8000 9090

# Start the FastAPI application with Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
